/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EntryForm: typeof import('./src/components/entries/EntryForm.vue')['default']
    EntryRow: typeof import('./src/components/entries/EntryRow.vue')['default']
    ManualEntryBar: typeof import('./src/components/entries/ManualEntryBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagInput: typeof import('./src/components/timer/TagInput.vue')['default']
    TimerWidget: typeof import('./src/components/timer/TimerWidget.vue')['default']
    WatchAccountMenu: typeof import('./src/components/WatchAccountMenu.vue')['default']
    WatchNavbar: typeof import('./src/components/WatchNavbar.vue')['default']
    WatchSidebar: typeof import('./src/components/WatchSidebar.vue')['default']
  }
}
